<?php

namespace AppBundle\Repository;

/**
 * QRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QRRepository extends \Doctrine\ORM\EntityRepository
{
}
