<?php

namespace AppBundle\Repository;

/**
 * StudentAttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentAttendanceRepository extends \Doctrine\ORM\EntityRepository
{
}
