# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }

    firewalls:
     # Custom authentication firewall for all request thats starts from /api
         api:
             pattern: ^/api/(?!token)
             guard:
                 authenticators:
                     - app.jwt_token_authenticator

    access_control:
         - { path: /api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api/home, roles: [ROLE_USER, ROLE_API_USER] }
